osx_image: xcode7.1
language: swift
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
before_install:
  - brew update || brew update
  - brew outdated xctool || brew upgrade xctool
  - gem install bundle
  - bundle install
  - xcrun simctl list
install: echo "<3"
script: fastlane test
