osx_image: xcode7.1
rvm:
  - 2.2.1
language: objective-c
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
before_install:
  - gem install bundle
  - bundle install
script:
  # - set -o pipefail
  - fastlane test
